### PR TITLE
Clamp set value feature

### PR DESCRIPTION
**Pull request by Garulf**
Works for the most part based on what you had proposed. 

Slider doesn't update its value to min/max value if changed in quick succession though. This was tested on fan, media_player, and light. I don't have a cover entity to test against.

### CODE REVIEW

**Comment by AnthonMS** [comment]
I can sign of on the first 2 commits. But I'm not following the home assistant service call functions. Why don't you just before the call check if the inputtet value is below or above min/max value, if true -> use min/max value, if false -> use inputted value? 

What is your logic behind the service calls?

**Comment by Garulf** [comment]
You make a good point, I should check the value before making a service call. I'll fix it when I'm back at my PC.

**Comment by AnthonMS** [comment]
I think that would maybe make the code easier to write and read for future changes. Plus hopefully that will eradicate the bug you're describing, about it not working with quick changes.

**Comment by Garulf** [comment]
With its current behavior the user can slide to max and the service call will apply it's configured max. 

I feel if I throw away user input if it's beyond the threshold it'll only lead to confusing behavior. Without any info on what the threshold is on the GUI the user won't know when to stop. 

I should still check if the value is already at the threshold and stop unneeded service calls.

Does that make sense?

**Comment by Garulf** [comment]
Ah found the cause of the bug. Home assistant doesn't update the state of the entity if there's no change of value. Thus the front end doesn't update the slider.

**Comment by AnthonMS** [comment]
Yeah okay. Did you delete your other comment? Can't see it here only in the email.

**Comment by Garulf** [comment]
Yeah, I re-read your comment and felt I may have mis-read what you wrote.

Could you clarify what you mean by "just before the call check"? Should this check be within the function, or the caller?

**Comment by AnthonMS** [comment]
What I would have done was just in The _set functions, before calling ha service, making an if statement that checks if the inputtet value is below or above min/max values, if it is, then set the value to min or max before the HA call.

**Comment by Garulf** [comment]
Would this work better?

example:
```
_setFan(entityClass, value, minSet, maxSet) {
    if (value > maxSet) {
        var value = maxSet;
    else if (value < minSet){
        var value = minSet;
    }

    this.hass.callService("fan", "set_percentage", {
        entity_id: entityClass.entity_id,
        percentage: value
    });
```

**Comment by AnthonMS** [comment]
Well that is what I would have done, but I'm guessing that is what you indirectly do with the min and max functions. But I haven't used them before, so don't know what they do.

But please tell me if that's a dumb way of doing it and the same result as the min/max functions you're using. I'm always glad to learn new stuff.

**Comment by Garulf** [comment]
Well doesn't fix the bug, but it is easier to read.

**Comment by AnthonMS** [comment]
Yeah okay. But that also makes sense if it's because Home Assistant doesn't trigger for change because value wasn't changed. Maybe a workaround for that would quickly setting the value one below or above input value and quickly changing it to desired value. (I know that's a hacky way of approaching this, but just maybe, it would work)

But appreciate it, I will merge it now if you think it's fine. The bug was already happening before, just hadn't stumbled upon it. So it's not like it's incooperating new bugs into the code.

**Comment by Garulf** [comment]
Okay sounds reasonable, the feature works for the most part.

However before we merge what do you think of changing minValue/maxValue to minBar/maxBar.
This will help separate the two features, but may break setups using the old values.

**Comment by AnthonMS** [comment]
Good thinking, that would probably be a good idea!

**Pull request merged**
