### PR TITLE
Change color on state change

### PR DESCRIPTION
**Pull request by Garulf**
This will change the sliders colors depending on the configured entity's state.

Are the default colors acceptable?

### CODE REVIEW

**Comment by AnthonMS** [comment]
But why?

**Comment by Garulf** [comment]
Makes it very clear to the user if the entity is off or on at a glance

Added bonus its more Wife proof!

**Comment by AnthonMS** [comment]
Okay, yeah I only looked at the first commit which was just changed default values. I see the changes now. This is actually a very nice feature! Will definitely play around with this 👍 

I didn't look at the readme update, but if you want to make a preview gif and yaml example that would be awesome!

**Comment by Garulf** [comment]
Haha! The first commit by itself would be very confusing without context! I'll make the preview and example in a moment.

**Pull request merged**
