### PR TITLE
Feature switch lock toggle

### PR DESCRIPTION
**Pull request by Garulf**
This is a really silly feature but after getting the slider to update I couldn't not try it.

It basically turns the slider into a "slide-to-unlock" like older iPhone OS's had when first released.

### CODE REVIEW

**Comment by AnthonMS** [comment]
In the switch and lock, you pass the minBar as the value. Why is that?

**Comment by Garulf** [comment]
```
  }
  let elt = this.shadowRoot;
  elt.activeElement.value = Number(Math.max(minSet, minBar));
}
```
I assume you're talking about this piece of code. This just allows the bar to reset to the lowest value depending on what the user set in their config.

**Comment by AnthonMS** [comment]
No I'm talking about this code: 
```
<div class="slider-container" style="${styleStr}">
            <input name="foo" type="range" class="${entityClass.state}" style="${styleStr}" .value="${minBar}" min="${minBar}" max="${maxBar}" step="${step}" @change=${e => this._setLock(entityClass, e.target.value, minSet, maxSet)}>
          </div>
```

**Comment by Garulf** [comment]
Ah, I wanted its initial state to be the lowest setting.

I should change it to `Number(Math.max(minSet, minBar));` to make sure.

**Comment by AnthonMS** [comment]
But shouldn't the value be dynamic on some kind of condition for the states? Or does that not matter at all when just setting the value on the shadowRoot?

**Comment by Garulf** [comment]
The way it is set up the thumb always resets to the left most point no matter the state. State is reflected in the cards color scheme.

So the user always slides right to activate. 

Does that make sense?

**Comment by AnthonMS** [comment]
Aahhh okay, that makes sense! I was thinking how it could ever be swiped right. Okay, yeah I see. But it still toggles it on/off & lock/unlock when sliding it to the right?

**Comment by Garulf** [comment]
Slider always starts on the right, swiping to far left toggles the switch/lock (this threshold can be changed with maxSet).
The slider always resets to minimum after release.

**Pull request merged**
